JavaAssignment/src/manasG/HelloManas.java
=> Adding My File

JavaAssignment/src/sneahaal/HelloWorldSneahaal.java, JavaAssignment/src/sneahaal/TestCheck.java
=> Added new file and updated Testcheck.java

JavaAssignment/src/gayatri/HelloWorld.java
=> Adding files for Gayatri

JavaAssignment/src/pradnya/Program6.java
Temperature Conversion Program No. 6
=> Assignment Q6

JavaAssignment/src/pradnya/Calculation.java, JavaAssignment/src/pradnya/ClientCalculation.java
Question 1 - Calculation Program
=> AssignmentQ1 Calculation Program

JavaAssignment/src/pradnya/SwapProgram1.java
Question 9 : Swapp two no without using third varible.
=> Program 9 Swap two no. without using third variable

JavaAssignment/src/pradnya/Prgram_5.java
Added Program 5: Simple Interest
=> Assignment Q5 Simple interest program

JavaAssignment/src/pradnya/ClientStudent.java, JavaAssignment/src/pradnya/ServerStudent.java
=> Adding Program 2

JavaAssignment/src/gayatri/Celsius.java
Q6 Convert Temp from Fahrenheit to celsius
=> convert Temprature

JavaAssignment/src/pradnya/PrimeNumber.java
Pragoram 10 : Prime number count
=> Program no. 10 Prime number count

JavaAssignment/src/amrutaC/Assignment_Q7.java
Write a Java program to convert seconds to hour, minute and seconds.
=> Assignment1_Q7_AmrutaC

JavaAssignment/src/pradnya/ClientProgram3.java, JavaAssignment/src/pradnya/ClientQuestion4.java, JavaAssignment/src/pradnya/ClientStudent.java, JavaAssignment/src/pradnya/ServerProgram3.java, JavaAssignment/src/pradnya/ServerQuestion4.java
=> Assignment q4 pradnya

JavaAssignment/src/amrutaC/Assignment_Q10.java
WAP to check find sum of all prime number between user given range.
=> Assignment1_Q10_AmrutaC

JavaAssignment/src/pradnya/TimeConversion.java
=> Assignment Q7

JavaAssignment/src/gayatri/Seconds.java
Q7 WAP to convert Sec to hrs,min and sec
=> convert sec to hrs

JavaAssignment/src/gayatri/SimpleInterest.java
=> Simple Interest

JavaAssignment/src/gayatri/StudentInfo.java
=> GayatriChavan_Assignmen1_Q2

JavaAssignment/src/pradnya/SwapProgram_2.java
=> Adding Program 8 Swapping using third variable

JavaAssignment/src/amrutaC/Assignment_Q9.java
WAP to swap two numbers without using the third variable.
=> Assignment1_Q9_AmrutaC

JavaAssignment/src/amrutaC/Assignment_Q8.java
WAP to swap two numbers using the third variable
=> Assignment1_Q8_AmrutaC

JavaAssignment/src/amrutaC/Assignment_Q6.java
Write a Java program to convert temperature from Fahrenheit to Celsius degree. Celsius = (fahrenheit - 32) * 5 / 9
=> Assignment1_Q6_AmrutaC

JavaAssignment/src/amrutaC/Assignment_Q5.java
Write a Java program to compute simple interest
Simple Interest = (P x T x R)/100 Where, P is the principle amount T is the time [year] and R is the rate
=> Assignment1_Q5_AmrutaC

JavaAssignment/src/amrutaC/Assignment_Q4.java
WAP to find the area and perimeter of Rectangle & Circle
=> Assignment1_Q4_AmrutaC

JavaAssignment/src/amrutaC/Assignment_Q3.java
WAP to find the square and cube of a number
=> Assignment1_Q3_AmrutaC

JavaAssignment/src/amrutaC/Assignment_Q2.java
WAP to print the details of Student As Roll No, Name and Marks by taking input from the user.
=> Assignment1_Q2_AmrutaC

JavaAssignment/src/sneahaal/SGA1Q10PrimeCheck.java, JavaAssignment/src/sneahaal/SGA1Q10SumOfPrime.java
Assignment 1 Q 10 - Sum of Prime nos in range given by user
=> Assignment_Q10_SneahaalGarge

JavaAssignment/src/sneahaal/SGA1Q9SwapWithoutThird.java
Assignment 1 Q 9 - Swap 2 nos without using third variable
=> Assignment_Q9_SneahaalGarge

JavaAssignment/src/sneahaal/SGA1Q8Swap3var.java
Assingment 1 Q 8 - Swap two variables using third variable.
=> Assignment_Q8_SneahaalGarge

JavaAssignment/src/sneahaal/SGA1Q7ConvertToSeconds.java
Assignment 1 Q 7 - Convert seconds to hr:Min:sec
=> Assignment_Q7_SneahaalGarge

JavaAssignment/src/sneahaal/SGA1Q6TempFToC.java
Assignment 1 Q 6 : Convert Temp from Fahrenheit to Celsius
=> Assignment_Q6_SneahaalGarge

JavaAssignment/src/sneahaal/SgA1Q5SimpleInterest.java
Assignment 1 Q 5 - Simple Interest
=> Assignment_Q5_SneahaalGarge

JavaAssignment/src/sneahaal/SGA1Q4AreaPeriClient.java, JavaAssignment/src/sneahaal/SGA1Q4AreaPerimeter.java
Assignment 1 Q 4 - Area and perimeter of Rectangle and Circle
=> Assignment_Q4_SneahaalGarge

JavaAssignment/src/manasG/AssignmentQ10.java
=> Adding file Question 10

JavaAssignment/src/manasG/AssignmentQ8.java
=> Adding question 8

JavaAssignment/src/manasG/AssignmentQ7.java
=> Adding question 7

JavaAssignment/src/manasG/AssignmentQ4.java
=> Adding file question 4

JavaAssignment/src/manasG/AssignmentQ2.java
=> Adding file student info

JavaAssignment/src/sneahaal/SGA1Q3SquareCube.java
Assignment 1 Q3 - Square and Cube for User given number
=> Assignment_Q3_SneahaalGarge

JavaAssignment/src/sneahaal/SGA1Q2Student.java
Assignment 1 Q2: Student details display
=> Assignment_Q2_SneahaalGarge

JavaAssignment/src/manasG/AssignmentQ9.java
=> Adding file question 9

JavaAssignment/src/sneahaal/Addition.java
Assignment 3 - Classes and Objects - Create a class Addition and write add method for:
* a) add two integers
* b) add two decimal
* c) add two String
=> Assignment3_ClassesAndObjects_Q6_SneahaalGarge

JavaAssignment/src/sneahaal/Book.java, JavaAssignment/src/sneahaal/BookClient.java
Assignment 3 - Class and Objects Q 5 - Create a class Book
=> Assignment3_ClassesAndObjects_Q5_SneahaalGarge

JavaAssignment/src/assignment4/Assignmen4_Q4.java, JavaAssignment/src/assignment4/Assignment4_Q1.java, JavaAssignment/src/assignment4/Assignment4_Q11.java, JavaAssignment/src/assignment4/Assignment4_Q12.java, JavaAssignment/src/assignment4/Assignment4_Q13.java, JavaAssignment/src/assignment4/Assignment4_Q3.java, JavaAssignment/src/assignment4/Assignment4_Q5.java, JavaAssignment/src/assignment4/Assignment4_Q7.java, JavaAssignment/src/assignment4/Assignment4_Q8.java
=> Assignment4

JavaAssignment/src/assignment4/Assignment4_Q10.java, JavaAssignment/src/assignment4/Assignment4_Q6.java, JavaAssignment/src/assignment4/Assignment4_Q9.java, JavaAssignment/src/assignment4/MaxLength.java
=> Assignment 4

JavaAssignment/src/sneahaal/Bank.java, JavaAssignment/src/sneahaal/BankClient.java
Assignment3_ClassObjects_Q2_ : Bank
=> Assignment3_ClassObjects_Q2_SneahaalGarge

JavaAssignment/src/sneahaal/Square.java, JavaAssignment/src/sneahaal/SquareClient.java
Assignment3_ClassObjects_Q4 : Square and Area
=> Assignment3_ClassObjects_Q4_SneahaalGarge

JavaAssignment/src/sneahaal/Circle.java, JavaAssignment/src/sneahaal/CircleClient.java
Assignment3_ClassObjects_Q1 ;  Circle
=> Assignment3_ClassObjects_Q1_SneahaalGarge

JavaAssignment/src/sneahaal/Employee.java, JavaAssignment/src/sneahaal/EmployeeClient.java
Assignment3_ClassObject_Q7 : Employee Class
=> Assignment3_ClassObject_Q7_SneahaalGarge

JavaAssignment/src/assignment3/Area.java, JavaAssignment/src/assignment3/Circle.java, JavaAssignment/src/assignment3/ClientCircle.java, JavaAssignment/src/assignment3/Program3.java, JavaAssignment/src/assignment3/Program6.java
Assignment no 3 - 4 Programs completed
=> Pradnya Assignment 3

JavaAssignment/src/yogeshS/Assignment1_Q1.java, JavaAssignment/src/yogeshS/Assignment1_Q1C.java
Adding one java file for Assignment Q1
=> Assignment1_Q1_YogeshS

JavaAssignment/src/Neelima/AssignmentQ1_JBP.java, JavaAssignment/src/Neelima/HelloJava.java
=> HelloAssignment01

JavaAssignment/src/sneahaal/SGA2Q10DiffIndexAllMax.java
Assignment 2 Q 10 - Find max value at differed index
=> Assignment2_Q10_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q9DiffIndexAll.java
Assignment 2 Q 9 - Find all differ index from given arrays
=> Assignment2_Q9_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q8DiffIndex.java
Assignment 2 Q 8 - Find first differ index from given arrays
=> Assignment2_Q8_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q7PairInArray.java
Assignment 2 Q 7 - Find all pairs on integer array whose sum is equal to given number
=> Assignment2_Q7_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q6EqualArray.java
Assignment 2 Q 6 - Check if 2 arrays are equal
=> Assignment2_Q6_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q5SecondLargest.java
Assignment 2 Q 5 - Find second largest element in an array of integers
=> Assignment2_Q5_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q4LargestSmallest.java
Assignment 2 Q 4 - Largest and smallest number in unsorted array
=> Assignment2_Q4_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q3CheckNum.java
Assignment 2 Q 3 - Check if array contains a number
=> Assignment2_Q3_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q2DuplicateNo.java
Assignment 2 - Q 2 - Duplicate nos in Array
=> Assignment2_Q2_SneahaalGarge

JavaAssignment/src/sneahaal/SGA2Q1MissingNumber.java
Assignment 1 Q1  : Missing number in range of 1 -10 from user given input
=> Assignment2_Q1_SneahaalGarge

JavaAssignment/src/gayatri/AllDifferIndex.java, JavaAssignment/src/gayatri/DuplicateNum.java, JavaAssignment/src/gayatri/FirstDiffer.java, JavaAssignment/src/gayatri/IdentifyNum.java, JavaAssignment/src/gayatri/MaxValue.java, JavaAssignment/src/gayatri/MissingNumber.java, JavaAssignment/src/gayatri/SecondLargestNum.java, JavaAssignment/src/gayatri/SmallestLargestNum.java, JavaAssignment/src/gayatri/SumOfPair.java, JavaAssignment/src/gayatri/TwoArraysEqual.java
=> Assignment 2 regarding array
